baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Roman Volkov'
theme: 'PaperMod'
enableEmoji: true

minify:
    disableXML: true

params:
  profileMode:
    enabled: true
    title: "Roman Volkov" # optional default will be site title
    subtitle: "This is subtitle"
    imageUrl: "profile.png" # optional
    imageTitle: "Roman's profile picture" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

  env: production
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  author: "Roman Volkov"
  comments: false

privacy:
  vimeo:
      disabled: true
      simple: true

  twitter:
      disabled: false
      enableDNT: true
      simple: true

  instagram:
      disabled: false
      simple: true

  youtube:
      disabled: true
      privacyEnhanced: true
