baseURL = "https://romanvolkov.ru"
languageCode = "en-us"
theme = "PaperMod"
enableEmoji = true

[minify]
disableXML = true

[params]
env = "production"
defaultTheme = "auto"
disableThemeToggle = true
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
author = "Roman Volkov"
comments = false
hideFooter = false
rtl = false
keywords = ["blog", "page", "development", "photography", "roman volkov", "роман волков"]

  [params.profileMode]
  enabled = true
  title = "Hey, I'm Roman Volkov"
  subtitle = """iOS developer, mobile team leader and photographer based in Moscow, Russia. Currently working at Linearity GmbH, leading Canvas intergration / Rendering team for Vectornator app"""

  imageUrl = "profile.png"
  imageTitle = "Roman's profile picture"
  imageWidth = 200
  imageHeight = 200
  
    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

  [[params.socialIcons]]
  name = "linkedin"
  url = "http://linkedin.com/in/roman-volkov/"

  [[params.socialIcons]]
  name = "telegram"
  url = "http://t.me/romanvolkov"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/rvolkov"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/romanvolkov"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/romanvolkov"



[privacy.vimeo]
disabled = true
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = true
privacyEnhanced = true


