baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Roman Volkov'
theme: 'PaperMod'
enableEmoji: true

minify:
    disableXML: true

params:
    homeInfoParams:
      Title: Hi there wave
      Content: Can be Info, links, about...

    env: production
    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true

    author: "Roman Volkov"
    comments: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true
